name: Send JSON File to Postman

on:
  push:
    branches:
      - main

jobs:
  send-to-postman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download JSON file
      run: curl -O https://github.com/gabrielAnFran/api-json/blob/main/Azion%20-%20API%20Reference%20AAAAAAV3.postman_collection.json

    - name: Change file permissions
      run: chmod +x Azion%20-%20API%20Reference%20AAAAAAV3.postman_collection.json

    - name: Send JSON file to Postman API
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
        -d $(cat Azion%20-%20API%20Reference%20AAAAAAV3.postman_collection.json) \
        https://api.postman.com/collections/24751531-51954a52-01da-4700-ad65-536a6388165c/runs
