name: Download and Send JSON File to Postman

on:
  push:
    branches:
      - main

jobs:
  download-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JSON file
      run: curl -O https://github.com/gabrielAnFran/api-json/blob/main/Azion%20-%20API%20Reference%20AAAAAAV3.postman_collection.json

    - name: Send JSON file to Postman API
      uses: Anish-Agnihotri/postman-api-action@v1
      with:
        postman_api_key: ${{ secrets.POSTMAN_API_KEY }}
        request_url: https://api.postman.com/collections/24751531-51954a52-01da-4700-ad65-536a6388165c/runs
        request_body: '{"data": [{"body": $(cat Azion%20-%20API%20Reference%20AAAAAAV3.postman_collection.json)}]}'
